services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apis_publicas_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"