name: Teste Actions

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Teste inicial
        run: echo "GitHub Actions funcionando"